export const projectData = [
  {
    id: 1,
    project: "Qkart_Store",
    js: "93.7%",
    html: "1.4%",
    css: "4.8%",
    date: "March 7, 2023",
    repoName: "Qkart_Store",
  },
  {
    id: 2,
    project: "Qtify",
    js: "74.7%",
    html: "6.4%",
    css: "18.8%",
    date: "July 22, 2023",
    repoName: "Qtify",
  },
  {
    id: 3,
    project: "Admin_UI",
    js: "86.3%",
    html: "2.9%",
    css: "10.8%",
    date: "Aug 13, 2023",
    repoName: "Admin_UI",
  },
  {
    id: 4,
    project: "Density_Exchange_LandingPage",
    js: "100%",
    html: "0%",
    css: "0%",
    date: "Nov 3, 2023",
    repoName: "Density_Exchange_LandingPage",
  },
];
